import {STORAGE_KEY,ITERATIONS,categories,incomeCategories,derive,seal,open,validateEnvelope,validateData,validDate} from './vault.js';
const framed=(()=>{try{return window.top!==window.self;}catch{return true;}})();if(framed){try{window.top.location=window.self.location.href;}catch{}}
const $=s=>document.querySelector(s),root=$('#root');let data=null,key=null,salt=null,iterations=ITERATIONS,page='overview',month=today().slice(0,7),search='',filter='all',busy=false,lastActivity=Date.now(),pendingImport=null,enter='enter',monthDir='',pickerYear=null;
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function escape(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function money(c){return new Intl.NumberFormat(undefined,{style:'currency',currency:data.currency,maximumFractionDigits:2}).format(c/100);}
function notify(s){const t=$('#toast');t.textContent=s;t.classList.remove('show');void t.offsetWidth;t.classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>t.classList.remove('show'),4000);}
function envelope(){const raw=localStorage.getItem(STORAGE_KEY);return raw?validateEnvelope(JSON.parse(raw)):null;}
const chevron=d=>`<svg viewBox="0 0 16 16" width="16" height="16" aria-hidden="true"><path d="${d<0?'M10 3 5 8l5 5':'M6 3l5 5-5 5'}" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>`;
function monthLabel(m,style='long'){const [y,mo]=m.split('-').map(Number);return new Date(y,mo-1,1).toLocaleDateString(undefined,{month:style,year:'numeric'});}
function shiftMonth(m,n){const [y,mo]=m.split('-').map(Number),d=new Date(y,mo-1+n,1);const next=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;return next>='1900-01'&&next<='9999-12'?next:m;}
function setMonth(next,dir){if(next===month)return;monthDir=dir||(next>month?'next':'prev');month=next;enter='refresh';render();}
function monthPicker(){return `<div class="month-picker" id="month-picker"><button type="button" class="mp-step" data-step="-1" aria-label="Previous month">${chevron(-1)}</button><button type="button" class="mp-label" id="month-toggle" aria-haspopup="dialog" aria-expanded="false" aria-controls="month-pop" aria-label="Selected month: ${monthLabel(month)}. Choose month"><span class="mp-text ${monthDir?'slide-'+monthDir:''}"><span class="mp-long">${monthLabel(month)}</span><span class="mp-short">${monthLabel(month,'short')}</span></span></button><button type="button" class="mp-step" data-step="1" aria-label="Next month">${chevron(1)}</button><div class="mp-pop" id="month-pop" role="dialog" aria-label="Choose month"><div class="mp-year"><button type="button" class="mp-round" data-year="-1" aria-label="Previous year">${chevron(-1)}</button><strong id="mp-year-label" aria-live="polite"></strong><button type="button" class="mp-round" data-year="1" aria-label="Next year">${chevron(1)}</button></div><div class="mp-grid" id="mp-grid"></div><div class="mp-foot"><button type="button" class="text-button" id="mp-today">This month</button></div></div></div>`;}
function pickerGrid(){const now=today().slice(0,7);$('#mp-year-label').textContent=pickerYear;$('#mp-grid').innerHTML=Array.from({length:12},(_,i)=>{const m=`${pickerYear}-${String(i+1).padStart(2,'0')}`,name=new Date(pickerYear,i,1).toLocaleDateString(undefined,{month:'short'});return `<button type="button" data-month="${m}" class="${m===month?'selected':''} ${m===now?'current':''}" aria-pressed="${m===month}" aria-label="${monthLabel(m)}${m===now?', current month':''}" tabindex="${m===month||(pickerYear!==+month.slice(0,4)&&i===0)?0:-1}">${name}</button>`;}).join('');}
function openPicker(){const pop=$('#month-pop');if(!pop)return;pickerYear=+month.slice(0,4);pickerGrid();pop.classList.add('open');$('#month-toggle').setAttribute('aria-expanded','true');requestAnimationFrame(()=>($('#mp-grid [tabindex="0"]')||$('#mp-grid button')).focus());}
function closePicker(focus=true){const pop=$('#month-pop');if(!pop||!pop.classList.contains('open'))return;pop.classList.remove('open');$('#month-toggle').setAttribute('aria-expanded','false');if(focus)$('#month-toggle').focus();}
function bindMonthPicker(){const mp=$('#month-picker');if(!mp)return;mp.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>setMonth(shiftMonth(month,+b.dataset.step)));$('#month-toggle').onclick=()=>$('#month-pop').classList.contains('open')?closePicker():openPicker();mp.querySelectorAll('[data-year]').forEach(b=>b.onclick=()=>{const y=pickerYear+ +b.dataset.year;if(y<1900||y>9999)return;pickerYear=y;const g=$('#mp-grid');g.classList.remove('slide-next','slide-prev');void g.offsetWidth;g.classList.add(+b.dataset.year>0?'slide-next':'slide-prev');pickerGrid();});$('#mp-grid').onclick=e=>{const b=e.target.closest('[data-month]');if(!b)return;closePicker(false);setMonth(b.dataset.month);$('#month-toggle')?.focus();};$('#mp-grid').onkeydown=e=>{const btns=[...$('#mp-grid').querySelectorAll('button')],i=btns.indexOf(document.activeElement),move={ArrowLeft:-1,ArrowRight:1,ArrowUp:-4,ArrowDown:4}[e.key];if(i<0||move===undefined)return;e.preventDefault();const j=Math.min(11,Math.max(0,i+move));btns.forEach((b,k)=>b.tabIndex=k===j?0:-1);btns[j].focus();};$('#mp-today').onclick=()=>{closePicker(false);setMonth(today().slice(0,7));$('#month-toggle')?.focus();};}
document.addEventListener('pointerdown',e=>{if($('#month-pop.open')&&!e.target.closest('#month-picker'))closePicker(false);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#month-pop.open')){e.preventDefault();closePicker();}});
const THEMES=[{"id":"glass","name":"Glass","scheme":"dark","bg":"#081424","swatches":["#081424","#9acbff","#8ae6cf"]},{"id":"soft-blush","name":"Soft Blush","scheme":"light","bg":"#ffe5ec","swatches":["#ffe5ec","#ffc2d1","#ffb3c6","#ff8fab","#fb6f92"]},{"id":"wine-plum","name":"Wine Plum","scheme":"dark","bg":"#2b141c","swatches":["#522e38","#602437","#8a2846","#b9375e","#e05780"]},{"id":"pine","name":"Pine & Sage","scheme":"dark","bg":"#1c2b23","swatches":["#344e41","#3a5a40","#588157","#a3b18a","#dad7cd"]},{"id":"frosted-mint","name":"Frosted Mint","scheme":"light","bg":"#e4fde1","swatches":["#e4fde1","#d5f5d2","#c6edc3","#a7dca5","#90cf8e"]},{"id":"crimson-silk","name":"Crimson Silk","scheme":"dark","bg":"#22050f","swatches":["#4a0d25","#b5bedd","#ffedd5"]},{"id":"nox-amethyst","name":"Nox Amethyst","scheme":"dark","bg":"#101010","swatches":["#141414","#7e49b3","#cfcfcf"]},{"id":"velvet-curfew","name":"Velvet Curfew","scheme":"dark","bg":"#151311","swatches":["#151311","#4b262f","#eed3ba"]},{"id":"marine-jade","name":"Marine Jade","scheme":"light","bg":"#fff5ee","swatches":["#ffcad4","#20b2aa","#fff5ee"]},{"id":"coral-rush","name":"Coral Rush","scheme":"light","bg":"#ffdbed","swatches":["#8e93cb","#f8769c","#ffdbed"]},{"id":"peony-espresso","name":"Peony & Espresso","scheme":"dark","bg":"#2a1916","swatches":["#f4c9d6","#3e2723"]},{"id":"fairy-tale","name":"Fairy Tale","scheme":"light","bg":"#ffceeb","swatches":["#ffceeb","#ff6634"]},{"id":"morning-butter","name":"Morning Butter","scheme":"light","bg":"#fbefc6","swatches":["#f3d98f","#e36887"]}],THEME_KEY='glass-ledger-theme';
function currentTheme(){const t=document.documentElement.dataset.theme;return THEMES.some(x=>x.id===t)?t:'glass';}
function applyTheme(id,{save=true,animate=false}={}){const t=THEMES.find(x=>x.id===id)||THEMES[0];const run=()=>{document.documentElement.dataset.theme=t.id;document.querySelector('meta[name=theme-color]')?.setAttribute('content',t.bg);};if(animate&&document.startViewTransition&&!matchMedia('(prefers-reduced-motion: reduce)').matches)document.startViewTransition(run);else run();if(save){try{localStorage.setItem(THEME_KEY,t.id);}catch{}}return t;}
applyTheme(currentTheme(),{save:false});
function colorway(){const cur=currentTheme();return `<article class="glass panel colorway"><div class="colorway-head"><h2>Colorway</h2><p>Applies right away on this browser, including the lock screen.</p></div><div class="theme-grid" role="radiogroup" aria-label="Colorway">${THEMES.map(t=>`<label class="theme-card" data-theme="${t.id}"><input type="radio" name="theme" value="${t.id}" ${t.id===cur?'checked':''}><span class="tc-preview" aria-hidden="true"><span class="tc-panel"><span class="tc-line"></span><span class="tc-line short"></span><span class="tc-bars"><i></i><i></i><i></i></span></span></span><span class="tc-meta"><span class="tc-name">${t.name}</span><span class="tc-swatches" aria-hidden="true">${t.swatches.map(c=>`<span style="background:${c}"></span>`).join('')}</span></span><span class="tc-check" aria-hidden="true"><svg viewBox="0 0 16 16" width="12" height="12"><path d="m3.5 8.5 3 3 6-7" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/></svg></span></label>`).join('')}</div></article>`;}
function brand(){return '<div class="brand"><span class="brand-mark">L</span>Glass Ledger</div>';}
function showAuth(){let exists=false;try{exists=!!envelope();}catch{exists=!!localStorage.getItem(STORAGE_KEY);}root.innerHTML=`<section class="auth-wrap"><div class="glass auth-card enter-card">${brand()}<div class="lock-symbol" aria-hidden="true">${exists?'⌑':'◇'}</div><p class="eyebrow">YOUR PRIVATE FINANCE SPACE</p><h1>${exists?'Welcome back.':'A little more clarity.'}</h1><p class="muted">${exists?'Enter your password to unlock your ledger.':'Create a password to start your personal ledger.'}</p><form id="auth-form"><label>Password<input name="password" type="password" required ${exists?'':'minlength="12"'} maxlength="256" autocomplete="${exists?'current-password':'new-password'}" placeholder="${exists?'Your vault password':'At least 12 characters'}"></label>${exists?'':'<label>Confirm password<input name="confirm" type="password" required maxlength="256" autocomplete="new-password"></label>'}<p id="auth-error" class="form-error" role="alert"></p><button class="primary" type="submit">${exists?'Unlock ledger':'Create my ledger'}</button></form><p class="auth-foot">Encrypted on this device. Your password never leaves your browser.</p><p class="auth-foot">${exists?'No password recovery. Keep your password and encrypted backups safe.':'There is no password recovery. Use a unique, strong password.'}</p><button class="text-button" id="auth-restore">Restore an encrypted backup</button></div></section>`;
$('#auth-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),password=f.get('password');if(!exists&&password!==f.get('confirm')){$('#auth-error').textContent='Passwords do not match.';return;}const button=e.target.querySelector('button');button.disabled=true;button.textContent=exists?'Unlocking…':'Creating…';try{let result;if(exists){result=await open(envelope(),password);}else{const newSalt=crypto.getRandomValues(new Uint8Array(16));const newKey=await derive(password,newSalt);const newData={currency:'PHP',transactions:[],budgets:{}};localStorage.setItem(STORAGE_KEY,JSON.stringify(await seal(newData,newKey,newSalt)));result={data:newData,key:newKey,salt:newSalt,iterations:ITERATIONS};}({data,key,salt,iterations}=result);lastActivity=Date.now();enter='enter';render();}catch{const card=$('.auth-card');if(card){card.classList.remove('enter-card','shake');void card.offsetWidth;card.classList.add('shake');}const err=$('#auth-error');if(err)err.textContent=exists?'Could not unlock. Check your password or restore a valid backup.':'Could not save your vault. Allow browser storage and use HTTPS or localhost.';}finally{button.disabled=false;button.textContent=exists?'Unlock ledger':'Create my ledger';}};
$('#auth-restore').onclick=async()=>{if(exists&&!await confirmation('Replace the locked ledger?','Restoring a backup permanently replaces the ledger saved on this device. It cannot be undone without its own backup.','Choose backup'))return;$('#backup-file').click();};}
function lock(){if(busy)return;enter='enter';data=null;key=null;salt=null;iterations=ITERATIONS;pendingImport=null;document.querySelectorAll('dialog').forEach(d=>{d.close();d.querySelectorAll('input').forEach(i=>i.value='');});showAuth();}
async function commit(next,newKey=key,newSalt=salt,newIterations=iterations){if(!data||busy)throw Error('Unlock your ledger first.');busy=true;try{validateData(next);const encrypted=await seal(next,newKey,newSalt,newIterations);localStorage.setItem(STORAGE_KEY,JSON.stringify(encrypted));data=next;key=newKey;salt=newSalt;iterations=newIterations;}finally{busy=false;}}
async function mutate(next,success){try{await commit(next);render();notify(success);return true;}catch(e){notify('Could not save. Your previous data is unchanged.');return false;}}
function totals(rows){return rows.reduce((a,t)=>{a[t.type]+=t.cents;return a;},{income:0,expense:0});}
function monthly(){return data.transactions.filter(t=>t.date.slice(0,7)===month);}
function heading(){return {overview:['Overview','Your money, at a glance.'],transactions:['Transactions','Every little detail, in one place.'],budgets:['Budgets','Make room for what matters.'],reports:['Reports','See the rhythm of your money.'],settings:['Settings','Your ledger. Your rules.']}[page];}
function render(){if(!data)return;const [title,subtitle]=heading();root.innerHTML=`<div class="shell"><aside class="sidebar">${brand()}<nav class="nav" aria-label="Main navigation">${[['overview','◫','Overview'],['transactions','≡','Transactions'],['budgets','◉','Budgets'],['reports','▥','Reports'],['settings','⚙','Settings']].map(([id,icon,label])=>`<button data-page="${id}" class="${page===id?'active':''}" ${page===id?'aria-current="page"':''}><span aria-hidden="true">${icon}</span>${label}</button>`).join('')}</nav><div class="sidebar-bottom"><p class="privacy-label">Encrypted vault<br>Stored on this device</p><button id="lock">Lock ledger</button></div></aside><section class="workspace"><header class="topbar"><div><p class="eyebrow">PERSONAL FINANCE</p></div><div class="top-actions">${page==='settings'?'':`${monthPicker()}<button class="primary" id="add">+ Add transaction</button>`}</div></header><div class="view ${enter||''}"><div class="greeting"><h1>${title}</h1><p>${subtitle}</p></div>${page==='settings'?settings():page==='transactions'?transactionView():page==='budgets'?budgetView():page==='reports'?reports():overview()}</div></section></div>`;enter=null;monthDir='';
root.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{if(page===b.dataset.page)return;page=b.dataset.page;enter='enter';render();window.scrollTo({top:0});});$('#lock').onclick=lock;if($('#add'))$('#add').onclick=()=>transactionDialog();bindMonthPicker();if($('#trend'))drawTrend(true);root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>transactionDialog(b.dataset.edit));root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteTransaction(b.dataset.delete));root.querySelectorAll('[data-budget]').forEach(b=>b.onclick=budgetDialog);if($('#view-all'))$('#view-all').onclick=()=>{page='transactions';enter='enter';render();};if($('#search')){$('#search').oninput=e=>{search=e.target.value;$('#transaction-table').innerHTML=table(filtered());bindRows();};$('#type-filter').onchange=e=>{filter=e.target.value;$('#transaction-table').innerHTML=table(filtered());bindRows();};}if(page==='settings')bindSettings();}
function bindRows(){root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>transactionDialog(b.dataset.edit));root.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteTransaction(b.dataset.delete));}
function statCards(){const t=totals(monthly()),net=t.income-t.expense;return `<div class="stats"><article class="glass stat featured"><div class="stat-label">Net this month</div><div class="stat-value ${net<0?'negative':''}">${money(net)}</div><p class="stat-caption">Income minus expenses</p></article><article class="glass stat"><div class="stat-label">Income</div><div class="stat-value positive">${money(t.income)}</div><p class="stat-caption">${monthly().filter(t=>t.type==='income').length} income transactions</p></article><article class="glass stat"><div class="stat-label">Expenses</div><div class="stat-value">${money(t.expense)}</div><p class="stat-caption">${monthly().filter(t=>t.type==='expense').length} expense transactions</p></article></div>`;}
function spending(){const sums=categories.map(c=>[c,monthly().filter(t=>t.type==='expense'&&t.category===c).reduce((s,t)=>s+t.cents,0)]).filter(([,n])=>n>0).sort((a,b)=>b[1]-a[1]);const total=sums.reduce((s,[,v])=>s+v,0);return sums.length?sums.map(([c,n],i)=>`<div class="spending-row"><div class="category-icon" aria-hidden="true">${i+1}</div><div class="row-title">${c}<div class="bar"><div class="bar-fill" style="width:${n/total*100}%"></div></div></div><div class="row-amount">${money(n)}<small>${Math.round(n/total*100)}%</small></div></div>`).join(''):'<div class="empty"><strong>No expenses yet</strong>Add an expense to see where your money goes.</div>';}
function budgetRows(limit=99){const entries=Object.entries(data.budgets).filter(([,v])=>v>0).slice(0,limit);return entries.length?entries.map(([c,b])=>{const spent=monthly().filter(t=>t.type==='expense'&&t.category===c).reduce((a,t)=>a+t.cents,0);return `<div class="spending-row ${spent>b?'over':''}"><div class="category-icon" aria-hidden="true">◉</div><div class="row-title">${c}<div class="bar"><div class="bar-fill" style="width:${Math.min(100,spent/b*100)}%"></div></div></div><div class="row-amount">${money(spent)} <small>of ${money(b)} · ${spent>b?'over by '+money(spent-b):money(b-spent)+' left'}</small></div></div>`;}).join(''):'<div class="empty"><strong>A plan for your spending</strong>Set category limits to start tracking your budgets.</div>';}
function overview(){return `${statCards()}<article class="glass panel trend-panel"><div class="section-head"><h2>Month to date</h2><div class="legend trend-legend" aria-hidden="true"><span class="exp">Spent</span><span class="inc">Income</span>${budgetTotal()>0?'<span class="pace">Budget pace</span>':''}</div></div><div class="trend" id="trend"></div></article><div class="grid-two"><article class="glass panel"><div class="section-head"><h2>Spending breakdown</h2><span class="pill">This month</span></div>${spending()}</article><article class="glass panel"><div class="section-head"><h2>Monthly budgets</h2><button data-budget>Manage</button></div>${budgetRows(4)}</article></div><article class="glass panel"><div class="section-head"><h2>Recent transactions</h2><button id="view-all">View all</button></div>${table(monthly().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5))}</article>`;}
function budgetTotal(){return Object.values(data.budgets).reduce((a,n)=>a+(n>0?n:0),0);}
function compact(c){try{return new Intl.NumberFormat(undefined,{style:'currency',currency:data.currency,notation:'compact',maximumFractionDigits:1}).format(c/100);}catch{return money(c);}}
function niceStep(max){const raw=max/4,p=10**Math.floor(Math.log10(raw)),f=raw/p;return (f<=1?1:f<=2?2:f<=2.5?2.5:f<=5?5:10)*p;}
let trendObserver=null;
function drawTrend(animate=true){const el=$('#trend');if(!el||!data)return;const [y,m]=month.split('-').map(Number),N=new Date(y,m,0).getDate(),now=today(),cur=now.slice(0,7);const last=month<cur?N:month>cur?0:Number(now.slice(8,10));
const inc=Array(N+1).fill(0),exp=Array(N+1).fill(0);for(const t of monthly()){const d=Number(t.date.slice(8,10));(t.type==='income'?inc:exp)[d]+=t.cents;}for(let d=1;d<=N;d++){inc[d]+=inc[d-1];exp[d]+=exp[d-1];}
const budget=budgetTotal(),top=Math.max(inc[last]||0,exp[last]||0,budget,1),step=niceStep(top),max=Math.ceil(top/step)*step||1;
const W=Math.max(280,el.clientWidth),H=el.clientHeight||230,L=Math.min(64,Math.max(46,W*.08)),R=12,T=10,B=26,pw=W-L-R,ph=H-T-B;
const X=d=>L+d/N*pw,Y=v=>T+ph-v/max*ph,pts=a=>Array.from({length:last+1},(_,d)=>`${X(d).toFixed(1)},${Y(a[d]).toFixed(1)}`);
const grid=[];for(let v=0;v<=max+1e-9;v+=step)grid.push(`<line x1="${L}" x2="${W-R}" y1="${Y(v).toFixed(1)}" y2="${Y(v).toFixed(1)}"/><text x="${L-8}" y="${(Y(v)+4).toFixed(1)}" text-anchor="end">${escape(compact(v))}</text>`);
const ticks=[1,8,15,22,N].filter((d,i,a)=>a.indexOf(d)===i&&(d===N||N-d>=4)).map(d=>`<text x="${X(d-.5).toFixed(1)}" y="${H-6}" text-anchor="middle">${d}</text>`).join('');
const e=pts(exp),i=pts(inc),has=last>0&&(exp[last]||inc[last]);
const svg=`<svg viewBox="0 0 ${W} ${H}" tabindex="0" role="group" aria-label="Month to date: ${has?`spent ${money(exp[last])}, income ${money(inc[last])}`:'no transactions yet'}. Use arrow keys to read each day.">
<defs><linearGradient id="trend-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" style="stop-color:var(--chart2);stop-opacity:.32"/><stop offset="1" style="stop-color:var(--chart2);stop-opacity:0"/></linearGradient></defs>
<g class="grid">${grid.join('')}</g>${ticks}
${budget>0?`<line class="pace" x1="${X(0)}" y1="${Y(0)}" x2="${X(N)}" y2="${Y(budget).toFixed(1)}"/>`:''}
${month===cur?`<line class="today" x1="${X(last).toFixed(1)}" x2="${X(last).toFixed(1)}" y1="${T}" y2="${T+ph}"/>`:''}
${has?`<path class="area" d="M${e.join(' L')} L${X(last).toFixed(1)},${Y(0)} L${X(0)},${Y(0)} Z"/><path class="line inc" pathLength="1" d="M${i.join(' L')}"/><path class="line exp" pathLength="1" d="M${e.join(' L')}"/>`:''}
<g class="hover"><line class="cross" y1="${T}" y2="${T+ph}"/><circle class="dot inc" r="4.5"/><circle class="dot exp" r="4.5"/></g></svg>
<div class="trend-tip" aria-live="polite"></div>${has?'':`<div class="trend-empty">${last?'No transactions this month yet.':'This month hasn’t started yet.'}</div>`}`;
el.innerHTML=svg;if(!animate)el.querySelectorAll('.line,.area').forEach(p=>p.style.animation='none');
const s=el.querySelector('svg'),tip=el.querySelector('.trend-tip'),cross=el.querySelector('.cross'),di=el.querySelector('.dot.inc'),de=el.querySelector('.dot.exp');let day=last;
function show(d){if(!has)return;day=Math.max(1,Math.min(last,d));const x=X(day);cross.setAttribute('x1',x);cross.setAttribute('x2',x);di.setAttribute('cx',x);di.setAttribute('cy',Y(inc[day]));de.setAttribute('cx',x);de.setAttribute('cy',Y(exp[day]));
const date=new Date(y,m-1,day).toLocaleDateString(undefined,{month:'short',day:'numeric'}),pace=budget?Math.round(budget*day/N):0;
tip.innerHTML=`<strong>Through ${escape(date)}</strong><span>Spent <b>${escape(money(exp[day]))}</b></span><span>Income <b>${escape(money(inc[day]))}</b></span>${budget?`<span>Budget pace <b>${escape(money(pace))}</b></span>`:''}`;
const tw=tip.offsetWidth,th=tip.offsetHeight,px=Math.min(Math.max(x-tw/2,0),W-tw),py=Math.max(0,Math.min(Y(Math.max(inc[day],exp[day]))-th-14,H-th));tip.style.left=px+'px';tip.style.top=py+'px';el.classList.add('active');}
function hide(){el.classList.remove('active');}
s.addEventListener('pointermove',ev=>{const r=s.getBoundingClientRect();show(Math.round(((ev.clientX-r.left)*(W/r.width)-L)/pw*N)||1);});
s.addEventListener('pointerleave',hide);s.addEventListener('focus',()=>show(day));s.addEventListener('blur',hide);
s.addEventListener('keydown',ev=>{const k={ArrowLeft:-1,ArrowRight:1,Home:-99,End:99}[ev.key];if(k===undefined)return;ev.preventDefault();show(day+k);});
if(!trendObserver&&window.ResizeObserver){let w=el.clientWidth,f=0;trendObserver=new ResizeObserver(()=>{const t=$('#trend');if(!t||Math.abs(t.clientWidth-w)<2)return;w=t.clientWidth;cancelAnimationFrame(f);f=requestAnimationFrame(()=>drawTrend(false));});}
if(trendObserver){trendObserver.disconnect();trendObserver.observe(el);}}
function table(rows){if(!rows.length)return '<div class="empty"><strong>No transactions here yet</strong>Add a transaction or choose another month.</div>';return `<div class="table-scroll"><table><thead><tr><th>Description</th><th>Category</th><th>Date</th><th class="amount">Amount</th><th><span class="muted">Actions</span></th></tr></thead><tbody>${rows.map(t=>`<tr><td>${escape(t.description)}${t.note?`<small>${escape(t.note)}</small>`:''}</td><td>${escape(t.category)}</td><td>${new Date(t.date+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</td><td class="amount ${t.type==='income'?'positive':''}">${t.type==='income'?'+':'−'}${money(t.cents)}</td><td><div class="row-buttons"><button data-edit="${escape(t.id)}" aria-label="Edit ${escape(t.description)}">Edit</button><button class="danger" data-delete="${escape(t.id)}" aria-label="Delete ${escape(t.description)}">Delete</button></div></td></tr>`).join('')}</tbody></table></div>`;}
function filtered(){return monthly().filter(t=>(filter==='all'||t.type===filter)&&`${t.description} ${t.category} ${t.note}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date));}
function transactionView(){return `${statCards()}<article class="glass panel"><div class="filters"><input id="search" placeholder="Search transactions" aria-label="Search transactions" value="${escape(search)}"><select id="type-filter" aria-label="Transaction type">${['all','income','expense'].map(t=>`<option value="${t}" ${filter===t?'selected':''}>${t==='all'?'All types':t==='income'?'Income':'Expenses'}</option>`).join('')}</select></div><div id="transaction-table">${table(filtered())}</div></article>`;}
function budgetView(){const budget=Object.values(data.budgets).reduce((a,n)=>a+n,0);return `<article class="glass panel"><div class="section-head"><h2>Category limits</h2><button class="primary" data-budget>Edit budgets</button></div><p class="muted">Total monthly budget: ${money(budget)}</p>${budgetRows()}</article>`;}
function chart(){const end=new Date(month+'-01T12:00:00');const series=Array.from({length:6},(_,i)=>{const d=new Date(end);d.setMonth(d.getMonth()-5+i);const m=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;return {label:d.toLocaleDateString(undefined,{month:'short'}),...totals(data.transactions.filter(t=>t.date.startsWith(m)))};});const max=Math.max(1,...series.flatMap(t=>[t.income,t.expense]));return `<div class="chart" role="img" aria-label="Income and expenses for six months ending in ${month}">${series.map(t=>`<div class="chart-group"><div class="chart-bars"><div class="chart-bar" style="height:${t.income/max*100}%" title="Income: ${money(t.income)}"></div><div class="chart-bar expense" style="height:${t.expense/max*100}%" title="Expenses: ${money(t.expense)}"></div></div><span class="chart-label">${t.label}</span></div>`).join('')}</div><div class="legend"><span>Income</span><span>Expenses</span></div><details style="margin-top:20px"><summary>View monthly figures</summary><div class="table-scroll"><table><thead><tr><th>Month</th><th>Income</th><th>Expenses</th></tr></thead><tbody>${series.map(t=>`<tr><td>${t.label}</td><td>${money(t.income)}</td><td>${money(t.expense)}</td></tr>`).join('')}</tbody></table></div></details>`;}
function reports(){const t=totals(monthly()),rate=t.income?Math.round((t.income-t.expense)/t.income*100):null;const all=totals(data.transactions);return `${statCards()}<div class="grid-two"><article class="glass panel"><div class="section-head"><h2>Cash flow</h2><span class="pill">6 months</span></div>${chart()}</article><article class="glass panel"><div class="section-head"><h2>Spending by category</h2></div>${spending()}</article></div><div class="stats"><article class="glass stat"><p class="stat-label">Savings rate this month</p><div class="stat-value">${rate===null?'—':rate+'%'}</div><p class="stat-caption">Share of income left after expenses</p></article><article class="glass stat"><p class="stat-label">All-time net</p><div class="stat-value">${money(all.income-all.expense)}</div><p class="stat-caption">Across all your recorded transactions</p></article><article class="glass stat"><p class="stat-label">Recorded transactions</p><div class="stat-value">${data.transactions.length}</div><p class="stat-caption">Across all months</p></article></div>`;}
function settings(){return `<div class="settings-grid">${colorway()}<article class="glass panel"><h2>Currency</h2><p>Choose the currency for your ledger. Changing this updates labels; it does not convert amounts.</p><label>Display currency<select id="currency">${['PHP','USD','EUR','GBP','JPY','CAD','AUD'].map(c=>`<option ${data.currency===c?'selected':''}>${c}</option>`).join('')}</select></label><button id="save-currency">Save currency</button></article><article class="glass panel"><h2>Backups & exports</h2><p>Download an encrypted backup regularly. Restore it on another device using its original password. Restoring replaces this device’s ledger.</p><div class="actions"><button id="backup">Encrypted backup</button><button id="restore">Restore backup</button><button id="csv">Export CSV</button></div><p>CSV exports are not encrypted. Keep them somewhere private.</p></article><article class="glass panel"><h2>Change password</h2><form id="password-form"><label>Current password<input name="current" type="password" autocomplete="current-password" required></label><label>New password<input name="new" type="password" minlength="12" maxlength="256" autocomplete="new-password" required></label><label>Confirm new password<input name="confirm" type="password" maxlength="256" autocomplete="new-password" required></label><p class="form-error" id="password-error" role="alert"></p><button type="submit">Update password</button></form></article><article class="glass panel"><h2>Privacy & security</h2><p class="security-note">Your financial records are encrypted with AES-256-GCM. Your password derives the encryption key using PBKDF2 with 600,000 iterations. Neither your password nor an unencrypted ledger is saved.</p><p>Locks automatically after 10 minutes of inactivity, and whenever you reload. Data lives only in this browser, on this website address. Clearing browser storage can erase it. There is no password recovery or automatic cloud sync.</p><p>Use HTTPS, keep your device secure, and save encrypted backups. Anyone can view the website’s public code, but unlocking your saved records requires your password.</p>${location.hostname.endsWith('.github.io')&&location.pathname.split('/').filter(Boolean).length?'<p class="security-note">This ledger runs at a shared address. Other GitHub Pages projects on this account share its browser storage and script permissions. For the strongest isolation, host it on its own domain or subdomain.</p>':''}</article></div>`;}
function setCategory(type,current){$('#category-select').innerHTML=(type==='expense'?categories:incomeCategories).map(c=>`<option ${current===c?'selected':''}>${c}</option>`).join('');}
function transactionDialog(id){if(busy)return;const f=$('#transaction-form');f.reset();$('#transaction-error').textContent='';const t=data.transactions.find(t=>t.id===id);$('#transaction-title').textContent=t?'Edit transaction':'Add transaction';f.elements.id.value=t?.id||'';f.elements.type.value=t?.type||'expense';setCategory(f.elements.type.value,t?.category);f.elements.description.value=t?.description||'';f.elements.amount.value=t?t.cents/100:'';f.elements.date.value=t?.date||today();f.elements.note.value=t?.note||'';$('#transaction-dialog').showModal();}
$('#transaction-form').elements.type.onchange=e=>setCategory(e.target.value);
$('#transaction-form').onsubmit=async e=>{e.preventDefault();if(busy||!data)return;const f=e.target,fields=new FormData(f),amount=Number(fields.get('amount')),cents=Math.round(amount*100),date=fields.get('date');if(!validDate(date)||!Number.isFinite(amount)||cents<=0||cents>99999999900){$('#transaction-error').textContent='Enter a valid amount and date (1900 or later).';return;}const t={id:fields.get('id')||crypto.randomUUID(),type:fields.get('type'),description:fields.get('description').trim(),cents,date,category:fields.get('category'),note:fields.get('note').trim()};if(!t.description){$('#transaction-error').textContent='Enter a description.';return;}const next=structuredClone(data),index=next.transactions.findIndex(r=>r.id===t.id);if(index>=0)next.transactions[index]=t;else next.transactions.push(t);const button=f.querySelector('[type=submit]');button.disabled=true;try{if(await mutate(next,'Transaction saved')){$('#transaction-dialog').close();f.reset();}}finally{button.disabled=false;}};
function confirmation(title,text,label='Delete'){const d=$('#confirm-dialog');$('#confirm-title').textContent=title;$('#confirm-text').textContent=text;d.querySelector('[value=yes]').textContent=label;d.returnValue='cancel';d.showModal();return new Promise(resolve=>d.addEventListener('close',()=>resolve(d.returnValue==='yes'),{once:true}));}
async function deleteTransaction(id){if(busy)return;if(await confirmation('Delete transaction?','This transaction will be permanently removed.')){if(!data)return;const next=structuredClone(data);next.transactions=next.transactions.filter(t=>t.id!==id);await mutate(next,'Transaction deleted');}}
function budgetDialog(){if(busy)return;$('#budget-error').textContent='';$('#budget-inputs').innerHTML=categories.map((c,i)=>`<div class="budget-field"><label for="budget-${i}">${c}</label><label><span class="muted" style="position:absolute;clip:rect(0,0,0,0)">${c} amount</span><input id="budget-${i}" data-category="${c}" type="number" min="0" max="999999999" step="0.01" value="${(data.budgets[c]||0)/100}" inputmode="decimal"></label></div>`).join('');$('#budget-dialog').showModal();}
$('#budget-form').onsubmit=async e=>{e.preventDefault();if(busy||!data)return;const next=structuredClone(data);next.budgets={};let bad=null;$('#budget-inputs').querySelectorAll('input').forEach(i=>{const v=i.value.trim()===''?0:Number(i.value),c=Math.round(v*100);if(!Number.isFinite(v)||c<0||c>99999999900)bad=bad||i.dataset.category;else next.budgets[i.dataset.category]=c;});if(bad){$('#budget-error').textContent=`Enter an amount from 0 to 999,999,999 for ${bad}.`;return;}$('#budget-error').textContent='';const b=e.target.querySelector('[type=submit]');b.disabled=true;try{if(await mutate(next,'Budgets saved'))$('#budget-dialog').close();}finally{b.disabled=false;}};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function bindSettings(){root.querySelectorAll('input[name=theme]').forEach(r=>r.onchange=()=>{if(r.checked){const t=applyTheme(r.value,{animate:true});notify(`Colorway: ${t.name}`);}});$('#save-currency').onclick=async()=>{if(busy)return;const next=structuredClone(data);next.currency=$('#currency').value;await mutate(next,'Currency saved');};$('#backup').onclick=()=>{try{download(JSON.stringify(envelope(),null,2),`glass-ledger-backup-${today()}.json`,'application/json');notify('Encrypted backup downloaded');}catch{notify('Could not export this vault.');}};$('#restore').onclick=()=>$('#backup-file').click();$('#csv').onclick=async()=>{if(!await confirmation('Export unencrypted CSV?','This file contains all your financial records in readable form. Keep it private.','Export'))return;if(!data)return;const cell=v=>{let s=String(v);if(/^[=+\-@\t\r\n]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};const rows=[['Date','Type','Description','Category','Amount','Currency','Note'],...data.transactions.map(t=>[t.date,t.type,t.description,t.category,(t.cents/100).toFixed(2),data.currency,t.note])];download('\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n'),`glass-ledger-${today()}.csv`,'text/csv;charset=utf-8');};$('#password-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const f=new FormData(e.target);if(f.get('new')!==f.get('confirm')){$('#password-error').textContent='New passwords do not match.';return;}const b=e.target.querySelector('button');b.disabled=true;try{await open(envelope(),f.get('current'));const s=crypto.getRandomValues(new Uint8Array(16)),k=await derive(f.get('new'),s);await commit(structuredClone(data),k,s,ITERATIONS);render();notify('Password updated. Make a new backup.');}catch{if($('#password-error'))$('#password-error').textContent='Could not change password. Check your current password and storage availability.';}finally{b.disabled=false;}};}
$('#backup-file').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file||busy)return;try{if(file.size>12000000)throw Error();pendingImport=validateEnvelope(JSON.parse(await file.text()));const dialog=document.createElement('dialog');dialog.id='restore-dialog';dialog.innerHTML='<form><div class="dialog-head"><h2>Restore backup</h2><button type="button" class="icon-button" aria-label="Close">×</button></div><p class="muted">Enter the password used for this backup. Restoring replaces the ledger stored on this device.</p><label>Backup password<input type="password" name="password" required autocomplete="current-password"></label><p class="form-error" role="alert"></p><div class="actions"><button type="button" id="restore-cancel">Cancel</button><button class="primary" type="submit">Restore ledger</button></div></form>';document.body.append(dialog);dialog.addEventListener('close',()=>{pendingImport=null;dialog.remove();});dialog.querySelector('.icon-button').onclick=()=>dialog.close();dialog.querySelector('#restore-cancel').onclick=()=>dialog.close();dialog.querySelector('form').onsubmit=async event=>{event.preventDefault();if(busy)return;const button=dialog.querySelector('[type=submit]');button.disabled=true;busy=true;try{const imported=pendingImport;const result=await open(imported,new FormData(event.target).get('password'));localStorage.setItem(STORAGE_KEY,JSON.stringify(imported));({data,key,salt,iterations}=result);lastActivity=Date.now();dialog.close();enter='enter';render();notify('Backup restored');}catch{dialog.querySelector('.form-error').textContent='Could not restore. Check the backup password and file. Your current ledger is unchanged.';}finally{busy=false;button.disabled=false;}};dialog.showModal();}catch{notify('This is not a valid Glass Ledger backup.');}};
let lastSeen=0;for(const event of ['pointerdown','keydown','touchstart','wheel','scroll','mousemove'])document.addEventListener(event,()=>{const now=Date.now();if(now-lastSeen<1000)return;lastSeen=now;if(data&&now-lastActivity>=600000&&!busy){lock();notify('Locked after inactivity');}lastActivity=now;},{passive:true,capture:true});
setInterval(()=>{if(data&&Date.now()-lastActivity>=600000&&!busy){lock();notify('Locked after inactivity');}},15000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&data&&Date.now()-lastActivity>=600000)lock();});
window.addEventListener('storage',e=>{if(e.key===THEME_KEY){applyTheme(e.newValue||'glass',{save:false});const r=root.querySelector(`input[name=theme][value="${currentTheme()}"]`);if(r)r.checked=true;return;}if(e.key===STORAGE_KEY&&data){if(busy){location.reload();return;}lock();notify('Vault changed in another tab. Unlock again.');}});
if(framed){root.innerHTML='<section class="auth-wrap"><div class="glass auth-card"><h1>Open Glass Ledger directly</h1><p>For your security, this ledger does not run inside another website.</p></div></section>';}else if(!window.isSecureContext||!crypto.subtle){root.innerHTML='<section class="auth-wrap"><div class="glass auth-card"><h1>Secure connection needed</h1><p>Open this website over HTTPS or localhost to use encrypted storage.</p></div></section>';}else showAuth();
