export const STORAGE_KEY='glass-ledger-v1';
export const ITERATIONS=600000,MIN_ITERATIONS=600000,MAX_ITERATIONS=5000000;
const enc=new TextEncoder(),dec=new TextDecoder();
const b64=bytes=>btoa(String.fromCharCode(...bytes));
const unb64=str=>Uint8Array.from(atob(str),c=>c.charCodeAt(0));
export const categories=['Food & dining','Shopping','Transport','Bills & utilities','Health','Entertainment','Addiction','Other'];
export const incomeCategories=['Salary','Freelance','Investments','Illegal Shits','Other'];
export async function derive(password,salt,iterations=ITERATIONS){const material=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
export async function seal(data,key,salt,iterations=ITERATIONS){const iv=crypto.getRandomValues(new Uint8Array(12));const bytes=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(data))));let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return {version:1,kdf:'PBKDF2-SHA256',iterations,salt:b64(salt),iv:b64(iv),ciphertext:btoa(binary)};}
export function validateEnvelope(e){if(!e||e.version!==1||e.kdf!=='PBKDF2-SHA256'||!Number.isSafeInteger(e.iterations)||e.iterations<MIN_ITERATIONS||e.iterations>MAX_ITERATIONS||typeof e.salt!=='string'||typeof e.iv!=='string'||typeof e.ciphertext!=='string'||e.ciphertext.length>15000000||unb64(e.salt).length!==16||unb64(e.iv).length!==12)throw Error('Invalid backup file.');return e;}
export function validateData(d){if(!d||!['PHP','USD','EUR','GBP','JPY','CAD','AUD','KRW','SGD', 'VND', 'THB'].includes(d.currency)||!Array.isArray(d.transactions)||d.transactions.length>50000||!d.budgets||typeof d.budgets!=='object'||Array.isArray(d.budgets))throw Error('Invalid finance data.');const ids=new Set();for(const t of d.transactions){if(!t||typeof t.id!=='string'||t.id.length>100||ids.has(t.id)||!['income','expense'].includes(t.type)||typeof t.description!=='string'||!t.description.trim()||t.description.length>100||typeof t.note!=='string'||t.note.length>300||![...categories,...incomeCategories].includes(t.category)||!(t.type==='expense'?categories:incomeCategories).includes(t.category)||!Number.isSafeInteger(t.cents)||t.cents<=0||t.cents>99999999900||!validDate(t.date))throw Error('Invalid transaction in backup.');ids.add(t.id);}for(const [k,v] of Object.entries(d.budgets)){if(!categories.includes(k)||!Number.isSafeInteger(v)||v<0||v>99999999900)throw Error('Invalid budget in backup.');}return d;}
export function validDate(v){return typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&v>='1900-01-01'&&v<='9999-12-31'&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v;}
export async function open(envelope,password){validateEnvelope(envelope);const salt=unb64(envelope.salt),key=await derive(password,salt,envelope.iterations);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(envelope.iv)},key,unb64(envelope.ciphertext));return {data:validateData(JSON.parse(dec.decode(plain))),key,salt,iterations:envelope.iterations};}
